spring:
  batch:
    job:
      names: ${job.name:NONE}
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:spring-batch-in-action;
    username: abc
    password: abc
  jpa:
    open-in-view: true
    properties:
      hibernate:
      show_sql: true
      format_sql: true
  h2:
    console:
      path: /h2
      enabled: true